### PR TITLE
De-emphasizing sp slot in SPC

### PR DESCRIPTION
**Pull request by brownag**
# Changes to spatial slot of the SoilProfileCollection
- Column names containing coordinate information and a string representing the spatial reference system are stored in SoilProfileCollection `@metadata` slot as `"coordinates"` and `"crs"`, respectively.
  - These are set w/ `coordinates(<SPC>) <- <formula/character>` and   `crs(<SPC>) <- <character/CRS>` 
- Adds {sf} to Suggests
  - Adds `as(<SPC>, 'sf')` method for coercion of site-level SPC data to `sf` data frame
    - Replaces {sp} internals of SoilProfileCollection coercion functions with {sf} functions
    - Now the SoilProfileCollection supports the concept of a profile with "empty" geometry, easing the wrangling of datasets that have mixed availability of coordinates. Such missing-data profile alongside profiles with data can be coerced to `sf` data frame but _not_ to `SpatialPointsDataFrame` or other sp-based classes.
  - Adds `crs<-`
    - `crs()` and `crs<-` are proposed as replacement for `proj4string()` 
    - {sf} `crs` object support has been added, also supports `authority:code` and integer EPSG code due to {sf} backend
    - <strike>consider alternate name for `wkt<-` considering other usages and various ways to specify CRS for sf/for an SPC</strike>
- Adds S4 definition for `coordinates(<SPC>) <- <character>` creating ability to set coordinates column names with a character vector 
- `validSpatialData()` now simply checks that coordinate column name metadata are defined and that the columns exist within the SoilProfileCollection object
  - this could be expanded to include some of the logic currently in the `as(<SPC>, 'sf')` method and/or additional stuff such as data type of columns
- `rebuildSPC()` has been updated: no longer propagates pre-existing data from the `@sp` slot to new `@sp` slot, but rather (re-)creates new columns in the `@site` slot and then sets metadata/CRS of the result accordingly. This allows its use to convert objects that were possibly saved with information in the `@sp` slot to a aqp 2.0 compatible representation

### CODE REVIEW

**Review by dylanbeaudette — COMMENTED** [review]
Great work, thanks for implementing these changes and the clever approach to fixing pre-2.0 SPC objects with data in `@sp`. Function names seem reasonable. I don't have a good alternative to `wkt`, but I think we both know how vague that acronym has become. I'll think about some alternatives. I'll run through all of my local examples and vignettes with this PR and report back.

**Comment by dylanbeaudette** [comment]
So far so good here on testing. No issues encountered.

**Comment by brownag** [comment]
1. `coordinates(<SPC>)` could return NULL in the event that `metadata(<SPC>)$coordinates` has zero-length, but currently there are several places that use something like `nrow(coordinates(<SPC>)) > 0` conditional which would break if we errored or were not returning something with  `nrow()` method defined. 
   - I didn't add any constraints on number, type, or name of "coordinates" in this PR... which could allow for e.g. a single column containing a sfc geometry or WKT string, one coordinate, XYZ/XYZM coordinates, etc. That said, for `coordinates()` default on uninitialized SPC I think it does make sense to return 2 (x, y) columns with 0 rows (what you get from `SpatialPoints(data.frame(x = 0, y = 0))[-1, ]@coords`)
 ``` r
library(aqp)
#> This is aqp 2.0
data(sp4)
depths(sp4) <- id ~ top + bottom
coordinates(sp4)
#>      x y
```

<sup>Created on 2023-01-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2. `<SPC>@metadata$projection` is now called `<SPC>@metadata$crs`

3. `crs()` and `crs()<-` are now used for getting and setting the CRS metadata respectively. The generic defs match `crs(x, ...)` pattern used in {terra} but are dispatched on SoilProfileCollection input

**Comment by dylanbeaudette** [comment]
@pierreroudier any thoughts on the matter? I'm keen to merge this PR after a couple more tests.

**Comment by dylanbeaudette** [comment]
Doing a quick check on winbuilder, and if all is clear then we should be good to merge. @pierreroudier we still have time for adjustments before a 2.0 release.

**Comment by brownag** [comment]
`revdepcheck::revdep_check()` indicates some reverse dependencies changed to worse by this PR:

- {soilassessment} has new warning in the examples due to deprecation of `aqp::proj4string()<-`. 
- {soilDB} checked locally (off CRAN) also has same problem in `fetchSoilGrids()` usages

I don't feel strongly about full deprecation here but thought it might be best to push users towards single/newer syntax.

---

Another possible issue for downstream: we want to make sure usage of `aqp::crs()` in soilDB/sharpshootR etc. is stable w/ possible masking of `crs()` when loading raster or terra after aqp. 
 - Any functions that get or set the CRS for an SPC should probably use `aqp::` prefix to be unambiguous. 
 - We will have similar method definition problem for coordinates/proj4string if/when we remove {sp} from imports (essentially the problem of: which package defines the generic? )

**Comment by dylanbeaudette** [comment]
Not related, but links to fix. I'll tackle these later today.

```
Found the following (possibly) invalid URLs:
  URL: http://cran.at.r-project.org/web/packages/sp/index.html (moved to http://cran.r-project.org/web/packages/sp/index.html)
    From: inst/doc/Introduction-to-SoilProfileCollection-Objects.html
    Status: 200
    Message: OK
  URL: http://cran.at.r-project.org/web/packages/sp/vignettes/intro_sp.pdf (moved to http://cran.r-project.org/web/packages/sp/vignettes/intro_sp.pdf)
    From: inst/doc/Introduction-to-SoilProfileCollection-Objects.html
    Status: 200
    Message: OK
  URL: https://github.com/ajesma/Pantoner/raw/gh-pages/csv/pantone-uncoated.csv
    From: man/pms.munsell.lut.Rd
    Status: 451
    Message: Unavailable For Legal Reasons
  URL: https://ncss-tech.github.io/AQP (moved to https://ncss-tech.github.io/AQP/)
    From: DESCRIPTION
    Status: 200
    Message: OK
  URL: https://raw.githubusercontent.com/ajesma/Pantoner/gh-pages/csv/pantone-coated.csv
    From: man/pms.munsell.lut.Rd
    Status: 404
    Message: Not Found
  URL: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/?cid=nrcs142p2_054184
    From: man/random_profile.Rd
    Status: 404
    Message: Not Found
  URL: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/edu/?cid=nrcs142p2_054286
    From: man/soil_minerals.Rd
    Status: 404
    Message: Not Found
  URL: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/ref/?cid=nrcs142p2_053569
    From: man/colorContrast.Rd
          man/contrastClass.Rd
    Status: 404
    Message: Not Found
  URL: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/research/guide/?cid=nrcs142p2_054184
    From: man/SoilTextureLevels.Rd
          man/hzDistinctnessCodeToOffset.Rd
          man/hzTopographyCodeToLineType.Rd
          man/hzTopographyCodeToOffset.Rd
    Status: 404
    Message: Not Found
  URL: https://www.soils.org/publications/sssaj/articles/73/6/2087
    From: inst/doc/Introduction-to-SoilProfileCollection-Objects.html
    Status: 503
    Message: Service Unavailable
```

**Comment by dylanbeaudette** [comment]
Quick note on this morning's conversation.

  * deprecate `coordinates()<-` and `proj4string()<-`
  * replacement is `initSpatial()<- ` with syntax following previous patterns: `initSpatial(spc, CRS) <- ~ x + y`
  * keep `sp` import for now, with Oct 1st 2023 deadline for removal
  * prioritize backwards compatibility with pre-1.42 SPCs for now

**Comment by dylanbeaudette** [comment]
fixed URLs

**Pull request merged**
