### PR TITLE
vectorize `perturb()`

### LINKED ISSUE #233: vectorization of perturb vs. new function?
I'm on the fence here: add some "safe" vectorization to `perturb` vs. a brand-new function. 

 * safe vectorization is always nice, but adds complexity
 * a simpler `perturb` is simpler to verify / optimize
 * a new function like `bootstrapProfile()` could include additional simulation: colors, properties, etc. without having to add complexity to `perturb`
 * ???

I do not have specific requirements in mind other than keeping aqp as organized as possible.

```r
library(aqp)
library(sharpshootR)
library(cluster)

# example data
data(sp4)
depths(sp4) <- id ~ top + bottom

# boundary variation parameter
horizons(sp4)$bdy <- 4

# iterate over profiles and simulate morphology
bootstrapProfile <- function(x, n, ...) {
  
  # SPC -> list of 1-element SPCs
  s <- split(x, f = profile_id(x))
  
  # iterate over list and simulate morphology
  res <- lapply(s, function(i) {
    
    # safe IDs
    pID <- profile_id(i)
    ids <- sprintf("%s-%03d", pID, 1:n)
    
    # simulate
    p <- perturb(i, id = ids, ...)
    return(p)
  })
  
  # flatten
  res <- combine(res)
  
  # TODO:  further simulation of properties / colors / etc.
  
  return(res)
}

# simulate three of each soil
b <- bootstrapProfile(sp4, n = 3, boundary.attr = 'bdy', min.thickness = 2)

# compare
d <- profile_compare(b, vars = c('ex_Ca_to_Mg', 'CEC_7'), max_d = 50, k = 0)
dd <- diana(d)

# viz
plotProfileDendrogram(b, dd, scaling.factor = 1.5, y.offset = 4, color = 'ex_Ca_to_Mg', width = 0.3, name.style = 'center-center', plot.depth.axis = FALSE, hz.depths = TRUE, cex.names = 0.65, col.label = 'Exchangeable Ca:Mg')
```

### PR DESCRIPTION
**Pull request by brownag**
PR to close #233

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Excited to see these developments. I'll do some local testing of this branch today.

**Comment by brownag** [comment]
You should hold off on testing until I have marked this PR ready for review, there are several more things I plan on changing and need to add more tests

**Comment by brownag** [comment]
OK, I think the fix was simpler/I was closer to the solution than I realized... just needed to step away for a bit. I think this is ready for review now

**Comment by dylanbeaudette** [comment]
Thanks for the work on this. Testing this branch this morning, with some code from the [perturb tutorial](https://ncss-tech.github.io/AQP/aqp/perturb.html). The first example, which is using fairly high SDs, is creating profiles 900+cm deep.

image

Later examples seem to have the same exaggeration of depth:
image

**Comment by brownag** [comment]
Thanks, there was a problem with the depth accumulation--an oversight from fixing one thing and checking another. On further reflection some code in there that was counterproductive. I've refactored a little bit in 63e0306e  and now get:

``` r
library(aqp)
#> This is aqp 2.0
library(soilDB)

# example profile
x <- fetchOSD(c('musick', 'drummer'))

# convert horizon distinctness codes into reasonable depth offsets
x$hd <- hzDistinctnessCodeToOffset(
  x$distinctness, 
  codes = c('very abrupt', 'abrupt', 'clear', 'gradual', 'diffuse')
)

# number of new IDs sets the number of realizations
s <- perturb(
  subset(x, id == 'MUSICK'), 
  id = sprintf("Sim. %02d", 1:9),
  boundary.attr = 'hd', 
  min.thickness = 5
)

# combine with original
o <- subset(x, id == 'MUSICK')

# combine multiple SPCs -> single SPC
s <- combine(
  o,
  s
)

# neat
par(mar=c(0,0,0,0))
plotSPC(s, name.style = 'center-center', plot.depth.axis = FALSE, hz.depths = TRUE, width = 0.3, cex.names = 0.75)
```



``` r

# example data
data(sp4)
depths(sp4) <- id ~ top + bottom

# simulated based on profile 1
p.idx <- 1

# use profile 6 as a "spike"
spike.idx <- 6

# simulate 
horizons(sp4)$bdy <- 4
set.seed(1010101)
p <- perturb(sp4[p.idx, ], n = 10, boundary.attr = 'bdy', min.thickness = 2)

# remove the old profile ID column
site(p)$id <- NULL

# combine: simulations + original + spike
z <- combine(
  p, 
  sp4[p.idx, ],
  sp4[spike.idx, ]
)

par(mar = c(0,0,3,0))
plotSPC(z, color = 'ex_Ca_to_Mg', width = 0.3, name.style = 'center-center', plot.depth.axis = FALSE, hz.depths = TRUE, cex.names = 0.75, col.label = 'Exchangeable Ca:Mg')
```

**Comment by dylanbeaudette** [comment]
Great. Thanks for fixing that so quickly. Good to go on merging.

**Pull request merged**
