### PR TITLE
Texture

### PR DESCRIPTION
**Pull request by smroecker**
Added 2 new texture conversion functions: fragvol_to_texmod() and texture_to_texmod().

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Looks good, do you have any suggestions for test cases? I'd be happy to write them.

**Comment by brownag** [comment]
This looks good to me. Really useful/important functionality I am glad to see 

I tested / tried to break it and didn't find any issues, docs were clear and error messages were informative.

Only thing I found was with  `texture_to_texmod()`--might need adjustment for the case where the texture is an in-lieu texture for fragmental textures e.g. `ASHY-BY` (ashy boulders), should return `NA` not `"by"`

``` r
library(aqp)
#> This is aqp 1.33
library(testthat)

## fragvol_to_texmod

# increasing volume of one size class
expect_equal(c("by", "byv", "byx", NA), fragvol_to_texmod(data.frame(boulders = c(25, 48, 75, 95)))$texmod)
expect_equal(c(NA, NA, NA, "by"), fragvol_to_texmod(data.frame(boulders = c(25, 48, 75, 95)))$lieutex)

# 2:1 rules for dominant/largest size class
expect_equal("cbx", fragvol_to_texmod(data.frame(gravel = 20, cobbles = 40))$texmod)
expect_equal("grx", fragvol_to_texmod(data.frame(gravel = 40, cobbles = 20))$texmod)
             
# no fragments > 15%
expect_equal(NA_character_, fragvol_to_texmod(data.frame(gravel = 1, cobbles = 2, flagstones = 10))$texmod)

# sum of fragments plus parafragments >15%, but nopf<15 and pf<15
expect_equal("pgr", fragvol_to_texmod(data.frame(gravel = 14, paragravel = 2))$texmod)

## texture_to_texmod

# very cobbly loam (works)
expect_equal(texture_to_texmod("CBV-L"), "cbv")

# ashy cobbly sandy loam (works)
expect_equal(texture_to_texmod("ASHY-CB-SL"), "cb")

# ashy boulders (does not work)
expect_equal(texture_to_texmod("ASHY-BY"), NA_character_)
#> Error: texture_to_texmod("ASHY-BY") not equal to NA_character_.
#> 1/1 mismatches
#> x[1]: "by"
#> y[1]: NA
```

**Comment by smroecker** [comment]
Thanks for the feedback. Andrews tests look like a good start. I'll address when I get back from Thanksgiving break. Happy Thanksgiving!

**Comment by dylanbeaudette** [comment]
Thanks guys. Merge when you are happy and then I'll give one look-over. Busy week, no rush.

**Comment by dylanbeaudette** [comment]
I'd like to merge this, and resolve any remaining issues in the main branch. I have some changes to make in the main branch as well.

**Pull request merged**
