### PR TITLE
Add .TOP & .BOTTOM k-keywords

### PR DESCRIPTION
**Pull request by brownag**
This draft PR adds two new "k-keywords" `.TOP` & `.BOTTOM` that I was thinking might be useful. These new ones are j-index short-circuits like `.HZID` and `.NHZ` and they work with `.FIRST`/`.LAST`. 

These keywords aren't really necessary but are convenient for writing functions where the `horizonDepths()`  may need to be stored in an intermediate variable. There are a few places this could be used to simplify syntax internally

``` r
library(aqp)
#> This is aqp 2.0
data("jacobs2000", package = "aqp")

jacobs2000[, , .TOP]
#>  [1]   0  18  43  79 130 153 156   0  18  46  84 122 145   0  15  25  64  84 112
#> [20] 165   0  20  53  79 130 165 185   0  28  61 109 135   0  18  46  76 104 119
#> [39]   0  15  41  48  61  91 132 140
jacobs2000[, , .BOTTOM]
#>  [1]  18  43  79 130 153 156 213  18  46  84 122 145 213  15  25  64  84 112 165
#> [20] 175  20  53  79 130 165 185 203  28  61 109 135 183  18  46  76 104 119 168
#> [39]  15  41  48  61  91 132 140 152
jacobs2000[, , .TOP, .BOTTOM]
#>    top bottom
#> 1    0     18
#> 2   18     43
#> 3   43     79
#> 4   79    130
#> 5  130    153
#> 6  153    156
#> 7  156    213
#> 8    0     18
#> 9   18     46
#> 10  46     84
#> 11  84    122
#> 12 122    145
#> 13 145    213
#> 14   0     15
#> 15  15     25
#> 16  25     64
#> 17  64     84
#> 18  84    112
#> 19 112    165
#> 20 165    175
#> 21   0     20
#> 22  20     53
#> 23  53     79
#> 24  79    130
#> 25 130    165
#> 26 165    185
#> 27 185    203
#> 28   0     28
#> 29  28     61
#> 30  61    109
#> 31 109    135
#> 32 135    183
#> 33   0     18
#> 34  18     46
#> 35  46     76
#> 36  76    104
#> 37 104    119
#> 38 119    168
#> 39   0     15
#> 40  15     41
#> 41  41     48
#> 42  48     61
#> 43  61     91
#> 44  91    132
#> 45 132    140
#> 46 140    152
jacobs2000[, , .LAST, .TOP]
#> [1] 156 145 165 185 135 119 140
jacobs2000[, , .FIRST, .BOTTOM]
#> [1] 18 18 15 20 28 18 15
jacobs2000[, , .LAST, .TOP, .BOTTOM]
#>   top bottom
#> 1 156    213
#> 2 145    213
#> 3 165    175
#> 4 185    203
#> 5 135    183
#> 6 119    168
#> 7 140    152
```

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Great idea, thanks for implementing this. Seeing `x[, , .TOP, .BOTTOM]` took me a second to mentally parse. This is is similar to the older idiom:

```r
# x[, , .LAST, .BOTTOM]
profileApply(x, max)
```
 I like the new `k`-keywords better.

**Comment by brownag** [comment]
> Great idea, thanks for implementing this.

Glad you like it. I guess it is just syntactic sugar but I think it makes good use of the depth column names stored in `x`. 

> Seeing `x[, , .TOP, .BOTTOM]` took me a second to mentally parse. 

Yes, I mainly was just considering what the behavior would be if both keywords were specified and settled on a data.frame with both columns, using the `horizonDepths()` as column names.

I considered having an alias of this .TOP+.BOTTOM syntax: `x[, , .DEPTHS]` 

An aside: this also reminded me we have no `depths(<SPC>)` "get" method.
Compared to the above, I think we would probably want the get `depths()` to return the profile ID in the result, whereas the main utility of .TOP and .BOTTOM, imo, is getting the vectors of depths, possibly with a numeric j-index, and with/without other keywords.

**Comment by dylanbeaudette** [comment]
> I considered having an alias of this .TOP+.BOTTOM syntax: `x[, , .DEPTHS]`

That isn't a bad idea, time for a "keywords" vignette, mainly to help me remember.

Is it a bad idea to consider the cursed 'l' index for site/horizon columns? Half joking.
 
> An aside: this also reminded me we have no `depths(<SPC>)` "get" method. Compared to the above, I think we would probably want the get `depths()` to return the profile ID in the result, whereas the main utility of .TOP and .BOTTOM, imo, is getting the vectors of depths, possibly with a numeric j-index, and with/without other keywords.

I'd be fine with that... and to be honest, I thought we did have a method for getting depths (we don't). I think that in the past I was content with `horizonDepths()` and related. Go ahead and add the get method if you can think of a use case.

**Comment by brownag** [comment]
> > I considered having an alias of this .TOP+.BOTTOM syntax: `x[, , .DEPTHS]`
> 
> That isn't a bad idea, time for a "keywords" vignette, mainly to help me remember.

Good idea

> Is it a bad idea to consider the cursed 'l' index for site/horizon columns? Half joking.

We relatively easily could allow a subset of site/horizon columns in the "k" index. I suppose I've broken the seal with having the k index starting to return data.frames...

Something like `x[1, , .LAST, slope, sand, silt, clay]`  or `x[1, , .LAST, c(slope, sand, silt, clay)]` (get reduced SPC with 1st profile, last horizon, including "slope", "sand", "silt", "clay" columns) are very feasible; basically pass whatever data left after i+j subsetting to `reduceSPC()`, and lookup remaining non-special "keywords" against names in the SPC.

> > An aside: this also reminded me we have no `depths(<SPC>)` "get" method. Compared to the above, I think we would probably want the get `depths()` to return the profile ID in the result, whereas the main utility of .TOP and .BOTTOM, imo, is getting the vectors of depths, possibly with a numeric j-index, and with/without other keywords.
> 
> I'd be fine with that... and to be honest, I thought we did have a method for getting depths (we don't). I think that in the past I was content with `horizonDepths()` and related. Go ahead and add the get method if you can think of a use case.

OK can do. It is not too difficult to do manually, but it does just sortof reflect the other side of the depths<- set method. Currently `.hzMetadataNames()` includes this id+depth information plus optional metadata, but it is not exported.

**Comment by brownag** [comment]
This is good to go unless we want to add the column-subsetting bit I described in last comment. That is a good idea, but maybe better as its own PR

**Comment by dylanbeaudette** [comment]
Agreed, lets leave the column subsetting to another PR. Thanks, looks good to go.

**Pull request merged**
